### ISSUE TITLE
Compilation fails with file not found

### ISSUE THREAD

**Issue by cjg67** [aws-robotics/lex-common#7]
Hello,

I am attempting to build lex-common as a dependancy to building kmahjon.  It claims this as a dependancy for another package that is required to build.  I am getting the following error:

[ 33%] Building CXX object CMakeFiles/lex_common.dir/src/lex_common.cpp.o
In file included from /usr/include/aws/core/utils/memory/MemorySystemInterface.h:20,
                 from /usr/include/aws/core/utils/memory/AWSMemory.h:20,
                 from /usr/include/aws/core/utils/memory/stl/AWSAllocator.h:21,
                 from /usr/include/aws/core/utils/memory/stl/AWSString.h:20,
                 from /usr/include/aws/core/http/Scheme.h:20,
                 from /usr/include/aws/core/client/ClientConfiguration.h:19,
                 from /usr/include/aws_common/sdk_utils/parameter_reader.h:18,
                 from /usr/include/aws_common/sdk_utils/client_configuration_provider.h:16,
                 from /sources/frameworks/lex-common-1.0.0/lex_common/include/lex_common/lex_common.h:19,
                 from /sources/frameworks/lex-common-1.0.0/lex_common/src/lex_common.cpp:16:
/usr/include/c++/9.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lex_common.dir/build.make:63: CMakeFiles/lex_common.dir/src/lex_common.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:190: CMakeFiles/lex_common.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Please note that stdlib.h is most certainly on my system, I have even gone so far as to rebuild gcc from source code with the exact same error occuring.

root [ /sources/frameworks/lex-common-1.0.0/lex_common ]# locate stdlib.h

/usr/include/bash/include/ansi_stdlib.h
/usr/include/bits/stdlib.h
/usr/include/boost/cstdlib.hpp
/usr/include/c++/9.2.0/stdlib.h
/usr/include/c++/9.2.0/tr1/stdlib.h
/usr/include/freetype2/freetype/config/ftstdlib.h
/usr/include/schily/stdlib.h
/usr/include/stdlib.h
/usr/share/doc/python-3.8.0/html/tutorial/stdlib.html

This is building from your release tar ball and not from a git checkout.
How can I successfully compile your program?

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello,

Here is the full output including using verbose to make:

cmake -DCMAKE_INSTALL_PREFIX=/usr ..
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as static objects
-- Generating linux build config
-- Building project version: 1.6.53
-- Found AWS SDK for C++, Version: 1.6.53, Install Root:/usr, Platform Prefix:, Platform Dependent Libraries: pthread;crypto;ssl;z;curl
-- Using CATKIN_DEVEL_PREFIX: /sources/frameworks/lex-common-1.0.0/lex_common/build/devel
-- Using CMAKE_PREFIX_PATH: 
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Found PY_em: /usr/lib/python2.7/site-packages/em.pyc  
-- Using empy: /usr/lib/python2.7/site-packages/em.pyc
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /sources/frameworks/lex-common-1.0.0/lex_common/build/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.19
-- BUILD_SHARED_LIBS is on
-- Building tests using catkin
CMake Warning at /usr/share/catkin/cmake/test/gtest.cmake:151 (message):
  skipping gmock 'test_lex_common' in project 'lex_common' because gmock was
  not found
Call Stack (most recent call first):
  /usr/share/catkin/cmake/test/gtest.cmake:80 (_catkin_add_executable_with_google_test)
  /usr/share/catkin/cmake/test/gtest.cmake:54 (_catkin_add_google_test)
  /usr/share/aws_common/cmake/DefineTestMacros.cmake:51 (catkin_add_gmock)
  CMakeLists.txt:91 (add_common_gtest)


-- Configuring done
-- Generating done
-- Build files have been written to: /sources/frameworks/lex-common-1.0.0/lex_common/build
root [ /sources/frameworks/lex-common-1.0.0/lex_common/build ]# make VERBOSE=1
/usr/bin/cmake -S/sources/frameworks/lex-common-1.0.0/lex_common -B/sources/frameworks/lex-common-1.0.0/lex_common/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /sources/frameworks/lex-common-1.0.0/lex_common/build/CMakeFiles /sources/frameworks/lex-common-1.0.0/lex_common/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/sources/frameworks/lex-common-1.0.0/lex_common/build'
make -f CMakeFiles/lex_common.dir/build.make CMakeFiles/lex_common.dir/depend
make[2]: Entering directory '/sources/frameworks/lex-common-1.0.0/lex_common/build'
cd /sources/frameworks/lex-common-1.0.0/lex_common/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /sources/frameworks/lex-common-1.0.0/lex_common /sources/frameworks/lex-common-1.0.0/lex_common /sources/frameworks/lex-common-1.0.0/lex_common/build /sources/frameworks/lex-common-1.0.0/lex_common/build /sources/frameworks/lex-common-1.0.0/lex_common/build/CMakeFiles/lex_common.dir/DependInfo.cmake --color=
Dependee "/sources/frameworks/lex-common-1.0.0/lex_common/build/CMakeFiles/lex_common.dir/DependInfo.cmake" is newer than depender "/sources/frameworks/lex-common-1.0.0/lex_common/build/CMakeFiles/lex_common.dir/depend.internal".
Dependee "/sources/frameworks/lex-common-1.0.0/lex_common/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/sources/frameworks/lex-common-1.0.0/lex_common/build/CMakeFiles/lex_common.dir/depend.internal".
Scanning dependencies of target lex_common
make[2]: Leaving directory '/sources/frameworks/lex-common-1.0.0/lex_common/build'
make -f CMakeFiles/lex_common.dir/build.make CMakeFiles/lex_common.dir/build
make[2]: Entering directory '/sources/frameworks/lex-common-1.0.0/lex_common/build'
[ 33%] Building CXX object CMakeFiles/lex_common.dir/src/lex_common.cpp.o
/usr/bin/c++  -DPLATFORM_LINUX -DROS_BUILD_SHARED_LIBS=1 -I/sources/frameworks/lex-common-1.0.0/lex_common/include -I/sources/frameworks/lex-common-1.0.0/lex_common/aws_common -I/sources/frameworks/lex-common-1.0.0/lex_common/aws-cpp-sdk-core -I/sources/frameworks/lex-common-1.0.0/lex_common/aws-cpp-sdk-logs -I/sources/frameworks/lex-common-1.0.0/lex_common/aws-cpp-sdk-monitoring -I/sources/frameworks/lex-common-1.0.0/lex_common/aws-cpp-sdk-s3 -I/sources/frameworks/lex-common-1.0.0/lex_common/aws-cpp-sdk-kinesis -I/sources/frameworks/lex-common-1.0.0/lex_common/aws-cpp-sdk-iot -I/sources/frameworks/lex-common-1.0.0/lex_common/aws-cpp-sdk-lex -I/sources/frameworks/lex-common-1.0.0/lex_common/aws-cpp-sdk-polly -isystem /usr/share/aws_common/cmake/../../../include  -std=c++11 -fPIC -o CMakeFiles/lex_common.dir/src/lex_common.cpp.o -c /sources/frameworks/lex-common-1.0.0/lex_common/src/lex_common.cpp
In file included from /usr/include/aws/core/utils/memory/MemorySystemInterface.h:20,
                 from /usr/include/aws/core/utils/memory/AWSMemory.h:20,
                 from /usr/include/aws/core/utils/memory/stl/AWSAllocator.h:21,
                 from /usr/include/aws/core/utils/memory/stl/AWSString.h:20,
                 from /usr/include/aws/core/http/Scheme.h:20,
                 from /usr/include/aws/core/client/ClientConfiguration.h:19,
                 from /usr/include/aws_common/sdk_utils/parameter_reader.h:18,
                 from /usr/include/aws_common/sdk_utils/client_configuration_provider.h:16,
                 from /sources/frameworks/lex-common-1.0.0/lex_common/include/lex_common/lex_common.h:19,
                 from /sources/frameworks/lex-common-1.0.0/lex_common/src/lex_common.cpp:16:
/usr/include/c++/9.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lex_common.dir/build.make:63: CMakeFiles/lex_common.dir/src/lex_common.cpp.o] Error 1
make[2]: Leaving directory '/sources/frameworks/lex-common-1.0.0/lex_common/build'
make[1]: *** [CMakeFiles/Makefile2:190: CMakeFiles/lex_common.dir/all] Error 2
make[1]: Leaving directory '/sources/frameworks/lex-common-1.0.0/lex_common/build'
make: *** [Makefile:141: all] Error 2

**Comment by cjg67** [comment]
Hello,

I just attempted to disect this further and by editing :

/usr/include/c++/9.2.0/cstdlib

and removing  _next from this file and from /usr/include/c++/9.2.0/bits/std_abs.h
allows lex_common to compile and install.

I have no idea what implications doing this will have on future compiles with my gcc installation.

Is this a new feature in this version of gcc that you have to alter your program for?  Or is it a bug introduced by gcc in this release?

Regards,

Christopher.

**Comment by ryanewel** [comment]
Hi cjg67,
We test this package on Ubuntu Xenial and Ubuntu Bionic with gcc version 5.4.0 and 7.4.0. Could you try compiling with one of those versions? 
What is kmahjon ? This package is intended to be a dependency of the lex-ros1 and lex-ros2 nodes.

**Comment by cjg67** [comment]
Hello,

I am unable to test this on such an old version of gcc, unfortunately.  kmahjong is a chinese board game for kde.

I have no idea why other developers are using this as a requirement, but it is happening and I had to install the full aws sdk as well.  However the program that required it, which is OpenAl, would not build against lex-common, it kept saying that it could not find it, so I had to disable the building of the example programs.

As I did manage to get lex-common to compile, I just thought it would be good for you to know that it will not compile with gcc 9.2.0.  I suspect from what others have told me that it is the way you are re-ordering things that has include_next not be able to find the include.

I have changed my files back to what they should be.

I am always rebuilding my system to up to date versions, I am not a programmer as I hate it with a passion.

Regards,

Christopher.

**Comment by mm318** [comment]
Hi @cjg67, sounds like you have been able to successfully compile this `lex-common` package with some version of a C++ compiler, so I'll close this issue for now. If you run into more difficulties, please don't hesitate to open another issue.

**Comment by cjg67** [comment]
That is a great head in the sand approach.  Most other people will be using gcc 9.2.0 as most of the other distros other than Ubuntu are releasing with that a stock.

The only way it worked was by removing the _next which should not have to be done.  It seems that you do not care that your program compiles on MODERN up to date compilers.  You would much rather waste peoples time because you do not know how to fix what you have broken.

I gave you a clue how to fix it.
